import React from "react";
import { Link } from "react-router-dom";
import Book from "../entities/Book";
import BookCard from "../components/BookCard";

const initialData = [
  new Book({
    bookId: 1,
    title: "JavaScript Mastery",
    author: { authorId: 1, name: "John Doe" },
    category: { categoryId: 2, name: "Programming" },
    price: 29.99,
    discount: 5.0,
    stockQuantity: 100,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "A comprehensive guide to mastering JavaScript.",
    publishedYear: 2023,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 2,
    title: "Learn React",
    author: { authorId: 2, name: "Jane Smith" },
    category: { categoryId: 3, name: "Web Development" },
    price: 39.99,
    discount: 10.0,
    stockQuantity: 50,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Everything you need to know to become a React expert.",
    publishedYear: 2022,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 3,
    title: "Python for Data Science",
    author: { authorId: 3, name: "Emily Johnson" },
    category: { categoryId: 4, name: "Data Science" },
    price: 49.99,
    discount: 15.0,
    stockQuantity: 25,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Master data science with Python programming.",
    publishedYear: 2021,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 1,
    title: "JavaScript Mastery",
    author: { authorId: 1, name: "John Doe" },
    category: { categoryId: 2, name: "Programming" },
    price: 29.99,
    discount: 5.0,
    stockQuantity: 100,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "A comprehensive guide to mastering JavaScript.",
    publishedYear: 2023,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 2,
    title: "Learn React",
    author: { authorId: 2, name: "Jane Smith" },
    category: { categoryId: 3, name: "Web Development" },
    price: 39.99,
    discount: 10.0,
    stockQuantity: 50,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Everything you need to know to become a React expert.",
    publishedYear: 2022,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 3,
    title: "Python for Data Science",
    author: { authorId: 3, name: "Emily Johnson" },
    category: { categoryId: 4, name: "Data Science" },
    price: 49.99,
    discount: 15.0,
    stockQuantity: 25,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Master data science with Python programming.",
    publishedYear: 2021,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 1,
    title: "JavaScript Mastery",
    author: { authorId: 1, name: "John Doe" },
    category: { categoryId: 2, name: "Programming" },
    price: 29.99,
    discount: 5.0,
    stockQuantity: 100,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "A comprehensive guide to mastering JavaScript.",
    publishedYear: 2023,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 2,
    title: "Learn React",
    author: { authorId: 2, name: "Jane Smith" },
    category: { categoryId: 3, name: "Web Development" },
    price: 39.99,
    discount: 10.0,
    stockQuantity: 50,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Everything you need to know to become a React expert.",
    publishedYear: 2022,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 3,
    title: "Python for Data Science",
    author: { authorId: 3, name: "Emily Johnson" },
    category: { categoryId: 4, name: "Data Science" },
    price: 49.99,
    discount: 15.0,
    stockQuantity: 25,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Master data science with Python programming.",
    publishedYear: 2021,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 1,
    title: "JavaScript Mastery",
    author: { authorId: 1, name: "John Doe" },
    category: { categoryId: 2, name: "Programming" },
    price: 29.99,
    discount: 5.0,
    stockQuantity: 100,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "A comprehensive guide to mastering JavaScript.",
    publishedYear: 2023,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 2,
    title: "Learn React",
    author: { authorId: 2, name: "Jane Smith" },
    category: { categoryId: 3, name: "Web Development" },
    price: 39.99,
    discount: 10.0,
    stockQuantity: 50,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Everything you need to know to become a React expert.",
    publishedYear: 2022,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 3,
    title: "Python for Data Science",
    author: { authorId: 3, name: "Emily Johnson" },
    category: { categoryId: 4, name: "Data Science" },
    price: 49.99,
    discount: 15.0,
    stockQuantity: 25,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Master data science with Python programming.",
    publishedYear: 2021,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 1,
    title: "JavaScript Mastery",
    author: { authorId: 1, name: "John Doe" },
    category: { categoryId: 2, name: "Programming" },
    price: 29.99,
    discount: 5.0,
    stockQuantity: 100,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "A comprehensive guide to mastering JavaScript.",
    publishedYear: 2023,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 2,
    title: "Learn React",
    author: { authorId: 2, name: "Jane Smith" },
    category: { categoryId: 3, name: "Web Development" },
    price: 39.99,
    discount: 10.0,
    stockQuantity: 50,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Everything you need to know to become a React expert.",
    publishedYear: 2022,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 3,
    title: "Python for Data Science",
    author: { authorId: 3, name: "Emily Johnson" },
    category: { categoryId: 4, name: "Data Science" },
    price: 49.99,
    discount: 15.0,
    stockQuantity: 25,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Master data science with Python programming.",
    publishedYear: 2021,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 1,
    title: "JavaScript Mastery",
    author: { authorId: 1, name: "John Doe" },
    category: { categoryId: 2, name: "Programming" },
    price: 29.99,
    discount: 5.0,
    stockQuantity: 100,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "A comprehensive guide to mastering JavaScript.",
    publishedYear: 2023,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 2,
    title: "Learn React",
    author: { authorId: 2, name: "Jane Smith" },
    category: { categoryId: 3, name: "Web Development" },
    price: 39.99,
    discount: 10.0,
    stockQuantity: 50,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Everything you need to know to become a React expert.",
    publishedYear: 2022,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 3,
    title: "Python for Data Science",
    author: { authorId: 3, name: "Emily Johnson" },
    category: { categoryId: 4, name: "Data Science" },
    price: 49.99,
    discount: 15.0,
    stockQuantity: 25,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Master data science with Python programming.",
    publishedYear: 2021,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 1,
    title: "JavaScript Mastery",
    author: { authorId: 1, name: "John Doe" },
    category: { categoryId: 2, name: "Programming" },
    price: 29.99,
    discount: 5.0,
    stockQuantity: 100,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "A comprehensive guide to mastering JavaScript.",
    publishedYear: 2023,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 2,
    title: "Learn React",
    author: { authorId: 2, name: "Jane Smith" },
    category: { categoryId: 3, name: "Web Development" },
    price: 39.99,
    discount: 10.0,
    stockQuantity: 50,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Everything you need to know to become a React expert.",
    publishedYear: 2022,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 3,
    title: "Python for Data Science",
    author: { authorId: 3, name: "Emily Johnson" },
    category: { categoryId: 4, name: "Data Science" },
    price: 49.99,
    discount: 15.0,
    stockQuantity: 25,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Master data science with Python programming.",
    publishedYear: 2021,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 1,
    title: "JavaScript Mastery",
    author: { authorId: 1, name: "John Doe" },
    category: { categoryId: 2, name: "Programming" },
    price: 29.99,
    discount: 5.0,
    stockQuantity: 100,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "A comprehensive guide to mastering JavaScript.",
    publishedYear: 2023,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 2,
    title: "Learn React",
    author: { authorId: 2, name: "Jane Smith" },
    category: { categoryId: 3, name: "Web Development" },
    price: 39.99,
    discount: 10.0,
    stockQuantity: 50,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Everything you need to know to become a React expert.",
    publishedYear: 2022,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 3,
    title: "Python for Data Science",
    author: { authorId: 3, name: "Emily Johnson" },
    category: { categoryId: 4, name: "Data Science" },
    price: 49.99,
    discount: 15.0,
    stockQuantity: 25,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Master data science with Python programming.",
    publishedYear: 2021,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 1,
    title: "JavaScript Mastery",
    author: { authorId: 1, name: "John Doe" },
    category: { categoryId: 2, name: "Programming" },
    price: 29.99,
    discount: 5.0,
    stockQuantity: 100,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "A comprehensive guide to mastering JavaScript.",
    publishedYear: 2023,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 2,
    title: "Learn React",
    author: { authorId: 2, name: "Jane Smith" },
    category: { categoryId: 3, name: "Web Development" },
    price: 39.99,
    discount: 10.0,
    stockQuantity: 50,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Everything you need to know to become a React expert.",
    publishedYear: 2022,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 3,
    title: "Python for Data Science",
    author: { authorId: 3, name: "Emily Johnson" },
    category: { categoryId: 4, name: "Data Science" },
    price: 49.99,
    discount: 15.0,
    stockQuantity: 25,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Master data science with Python programming.",
    publishedYear: 2021,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 1,
    title: "JavaScript Mastery",
    author: { authorId: 1, name: "John Doe" },
    category: { categoryId: 2, name: "Programming" },
    price: 29.99,
    discount: 5.0,
    stockQuantity: 100,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "A comprehensive guide to mastering JavaScript.",
    publishedYear: 2023,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 2,
    title: "Learn React",
    author: { authorId: 2, name: "Jane Smith" },
    category: { categoryId: 3, name: "Web Development" },
    price: 39.99,
    discount: 10.0,
    stockQuantity: 50,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Everything you need to know to become a React expert.",
    publishedYear: 2022,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
  new Book({
    bookId: 3,
    title: "Python for Data Science",
    author: { authorId: 3, name: "Emily Johnson" },
    category: { categoryId: 4, name: "Data Science" },
    price: 49.99,
    discount: 15.0,
    stockQuantity: 25,
    currency: { currencyCode: "USD", symbol: "$" },
    description: "Master data science with Python programming.",
    publishedYear: 2021,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    imageData:
      "https://w0.peakpx.com/wallpaper/536/1014/HD-wallpaper-anime-landscape-school-girl-back-view-clouds-anime.jpg",
  }),
];

const Products = () => {
  return (
    <div className="products py-6 bg-gray-200 w-full">
      <div className="products-container w-full max-w-screen-lg mx-auto px-5 mb-24">
        <div className="products__app-bar flex flex-row justify-between">
          <h1 className="products-title text-center text-2xl font-bold text-gray-800 mb-5">Products</h1>
          <Link to="/add-product" className="add-product-btn h-12 inline-block px-2 py-1 text-base font-bold text-gray-100 bg-blue-800 rounded-lg cursor-pointer transition-transform duration-200 shadow-md hover:scale-105 active:scale-95 focus:outline focus:outline-2 focus:outline-blue-800 focus:outline-offset-2">
            <h1>ADD new product</h1>
          </Link>
        </div>
        <div className="products-grid grid grid-cols-[repeat(auto-fill,_minmax(250px,_1fr))] gap-20">
          {initialData.map((book) => (
            <BookCard book={book}/>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Products;
